Fix transport code structure
sumelms/microservice-course pull request #18
Opened 2024-01-18 01:08 UTC by marianysilva

2024-01-20 22:08 UTC, rluders requested changes

2024-01-20 22:08 UTC, rluders commented on cmd/server/main.go
> +	http "github.com/sumelms/microservice-course/internal/shared"
remove o alias e usar shared, talvez?

2024-01-22 21:35 UTC, marianysilva commented on cmd/server/main.go
> +	http "github.com/sumelms/microservice-course/internal/shared"
Done [here](https://github.com/sumelms/microservice-course/pull/18/commits/f9d7c178d11b447e35a0fdc1a74855fecce110d7), ty.

2024-01-22 22:18 UTC, rluders approved these changes
lgtm

2024-01-22 22:18 UTC, merged